"""empty message

Revision ID: ccca93f1bbe8
Revises: 790075a0293e
Create Date: 2021-09-25 22:37:17.864891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccca93f1bbe8'
down_revision = '790075a0293e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date')
    op.drop_column('blogs', 'date')
    # ### end Alembic commands ###
